### ISSUE TITLE
occassionally segfaults when search is ended

### ISSUE THREAD

**Issue by hans-ekbrand** [hans-ekbrand/lc0#1]
See attached logfile.

[ab-helper-berserk.log](https://github.com/hans-ekbrand/lc0/files/7574534/ab-helper-berserk.log)

**Comment by hans-ekbrand** [comment]
Here is the output of `thread apply all backtrace` in `gdb`:
```
Thread 82 (Thread 0x7ffef77fe700 (LWP 12161)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7fffd38e8348) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7fffd38e82d0, cond=0x7fffd38e8320) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7fffd38e8320, mutex=0x7fffd38e82d0) at pthread_cond_wait.c:638
#3  0x00007fffd5ec690c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/local/cuda/lib64/libstdc++.so.6
#4  0x000055555561581d in std::thread::_State_impl<std::thread::_Invoker<std::tuple<lczero::SearchWorker::SearchWorker(lczero::Search*, lczero::SearchParams const&, int)::{lambda()#1}> > >::_M_run() ()
#5  0x00007fffd5ecbed0 in ?? () from /usr/local/cuda/lib64/libstdc++.so.6
#6  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 81 (Thread 0x7ffef7fff700 (LWP 12160)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7fffd38e8348) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7fffd38e82d0, cond=0x7fffd38e8320) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7fffd38e8320, mutex=0x7fffd38e82d0) at pthread_cond_wait.c:638
#3  0x00007fffd5ec690c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/local/cuda/lib64/libstdc++.so.6
#4  0x000055555561581d in std::thread::_State_impl<std::thread::_Invoker<std::tuple<lczero::SearchWorker::SearchWorker(lczero::Search*, lczero::SearchParams const&, int)::{lambda()#1}> > >::_M_run() ()
#5  0x00007fffd5ecbed0 in ?? () from /usr/local/cuda/lib64/libstdc++.so.6
#6  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 80 (Thread 0x7fff04ffd700 (LWP 12159)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7fffd38e8348) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7fffd38e82d0, cond=0x7fffd38e8320) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7fffd38e8320, mutex=0x7fffd38e82d0) at pthread_cond_wait.c:638
#3  0x00007fffd5ec690c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/local/cuda/lib64/libstdc++.so.6
#4  0x000055555561581d in std::thread::_State_impl<std::thread::_Invoker<std::tuple<lczero::SearchWorker::SearchWorker(lczero::Search*, lczero::SearchParams const&, int)::{lambda()#1}> > >::_M_run() ()
#5  0x00007fffd5ecbed0 in ?? () from /usr/local/cuda/lib64/libstdc++.so.6
#6  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 79 (Thread 0x7fff057fe700 (LWP 12158)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7fffd38e8348) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7fffd38e82d0, cond=0x7fffd38e8320) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7fffd38e8320, mutex=0x7fffd38e82d0) at pthread_cond_wait.c:638
#3  0x00007fffd5ec690c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/local/cuda/lib64/libstdc++.so.6
#4  0x000055555561581d in std::thread::_State_impl<std::thread::_Invoker<std::tuple<lczero::SearchWorker::SearchWorker(lczero::Search*, lczero::SearchParams const&, int)::{lambda()#1}> > >::_M_run() ()
#5  0x00007fffd5ecbed0 in ?? () from /usr/local/cuda/lib64/libstdc++.so.6
#6  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 75 (Thread 0x7fffd38fa700 (LWP 12154)):
#0  0x00007fffa761c137 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#1  0x00007fffa77f6247 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fffa756d505 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fffa76192e0 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fffa761947f in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007fffa776a0b2 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007fffa776a274 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#7  0x00007fffa76186e9 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#8  0x00007fffa76188a0 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#9  0x00007fffa7542dda in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#10 0x00007fffa76e8d2f in cuCtxSynchronize () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#11 0x00007ffff190a139 in ?? () from /usr/local/cuda/lib64/libcudart.so.10.2
#12 0x00007ffff1948a19 in cudaDeviceSynchronize () from /usr/local/cuda/lib64/libcudart.so.10.2
#13 0x00005555555a6b8d in lczero::CudaNetworkComputation<__half>::ComputeBlocking() ()
#14 0x0000555555600f24 in lczero::Search::StartThreads(unsigned long)::{lambda()#2}::operator()() const [clone .isra.900] ()
#15 0x00007fffd5ecbed0 in ?? () from /usr/local/cuda/lib64/libstdc++.so.6
#16 0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#17 0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
Thread 73 (Thread 0x7fffb18f6700 (LWP 12152)):
#0  _int_free (av=0x7ffefc000020, p=0x7ffefc056540, have_lock=<optimized out>) at malloc.c:4316
#1  0x00005555556186d2 in lczero::SearchWorker::~SearchWorker() [clone .lto_priv.883] ()
#2  0x0000555555600d0a in lczero::Search::StartThreads(unsigned long)::{lambda()#2}::operator()() const [clone .isra.900] ()
#3  0x00007fffd5ecbed0 in ?? () from /usr/local/cuda/lib64/libstdc++.so.6
--Type <RET> for more, q to quit, c to continue without paging--
#4  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 71 (Thread 0x7fff857fe700 (LWP 12150)):
#0  __libc_read (nbytes=931, buf=0x555555cc637c, fd=3) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __libc_read (fd=3, buf=0x555555cc637c, nbytes=931) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00005555556155e8 in boost::process::basic_pipebuf<char, std::char_traits<char> >::underflow() ()
#3  0x00007fffd5ebaefa in std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char) () from /usr/local/cuda/lib64/libstdc++.so.6
#4  0x0000555555626258 in lczero::Search::AuxEngineWorker() ()
#5  0x00007fffd5ecbed0 in ?? () from /usr/local/cuda/lib64/libstdc++.so.6
#6  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7fff85fff700 (LWP 12077)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x7fff85fef3b0, clockid=-2046889152, expected=0, futex_word=0x55557392f2c8) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7fff85fef3b0, clockid=-2046889152, mutex=0x55557392f248, cond=0x55557392f2a0) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x55557392f2a0, mutex=0x55557392f248, abstime=0x7fff85fef3b0) at pthread_cond_wait.c:656
#3  0x00007fffa76802e7 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fffa7619617 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007fffa767f1d8 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7fffa0c32700 (LWP 12076)):
#0  0x00007fffd5bab3bf in __GI___poll (fds=0x7fff8c000c10, nfds=11, timeout=100) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fffa767c0db in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fffa773c64a in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fffa767f1d8 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fffa1433700 (LWP 12075)):
#0  0x00007fffd5bb7768 in accept4 (fd=13, addr=..., addr_len=0x7fffa1423378, flags=524288) at ../sysdeps/unix/sysv/linux/accept4.c:32
#1  0x00007fffa767d196 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fffa766e7bd in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fffa767f1d8 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fffa90f5700 (LWP 12071)):
#0  0x00007fffd5b7dc21 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffa90e5410, rem=0x7fffa90e5410) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
#1  0x00007fffd5b83403 in __GI___nanosleep (requested_time=<optimized out>, remaining=<optimized out>) at nanosleep.c:27
#2  0x0000555555618c97 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<lczero::(anonymous namespace)::NodeGarbageCollector::NodeGarbageCollector()::{lambda()#1}> > >::_M_run() [clone .lto_priv.599] ()
#3  0x00007fffd5ecbed0 in ?? () from /usr/local/cuda/lib64/libstdc++.so.6
#4  0x00007fffd5c85ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007fffd5bb5daf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fffd390d1c0 (LWP 12065)):
#0  __GI___libc_read (nbytes=1024, buf=0x555555cdc3e0, fd=0) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __GI___libc_read (fd=0, buf=0x555555cdc3e0, nbytes=1024) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007fffd5b3985a in _IO_new_file_underflow (fp=0x7fffd5c76980 <_IO_2_1_stdin_>) at libioP.h:948
#3  0x00007fffd5b3aac2 in __GI__IO_default_uflow (fp=0x7fffd5c76980 <_IO_2_1_stdin_>) at libioP.h:948
#4  0x00007fffd5b34f58 in _IO_getc (fp=0x7fffd5c76980 <_IO_2_1_stdin_>) at getc.c:38
#5  0x00007fffd5efa96d in __gnu_cxx::stdio_sync_filebuf<char, std::char_traits<char> >::underflow() () from /usr/local/cuda/lib64/libstdc++.so.6
#6  0x00007fffd5ebaefa in std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char) () from /usr/local/cuda/lib64/libstdc++.so.6
#7  0x000055555562dcb8 in lczero::UciLoop::RunLoop() ()
#8  0x0000555555636c60 in lczero::EngineLoop::RunLoop() ()
#9  0x00005555555878e2 in main ()
```
